version: '3'
services:
    rdb:
        image: rethinkdb
        container_name: rdb
        ports:
            - 8080:8080
            - 28015:28015
            - 29015:29015
        volumes:
            - rdb-data:/data
        command: rethinkdb --bind all --directory /data 
        restart: always

    api:
        image: api
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_ENV: development
        links:
            - rdb
        depends_on:
            - rdb
        ports:
            - 3000:3000
        volumes:
            - yarn:/home/node/.cache/yarn
            - ./.babelrc:/usr/src/app/.babelrc
            - ./.env:/usr/src/app/.env
            - ./server:/usr/src/app/server
            - ./build:/usr/src/app/build
            - ./package.json:/usr/src/app/package.json
            - ./yarn.lock:/usr/src/app/yarn.lock
        entrypoint: sh -c
        command: ["yarn dev"]
        restart: always

volumes:
    yarn:
    rdb-data: