version: '3'
services:
    api:
        image: api
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_ENV: development
        ports:
            - 3000:3000
        volumes:
            - yarn:/home/node/.cache/yarn
            - ./.babelrc:/usr/src/app/.babelrc
            - ./.env:/usr/src/app/.env
            - ./server:/usr/src/app/server
            - ./build:/usr/src/app/build
            - ./package.json:/usr/src/app/package.json
            - ./yarn.lock:/usr/src/app/yarn.lock
        entrypoint: sh -c
        command: yarn dev

volumes:
    yarn:
