# This will boot 4 mongoDB containers:
# 3 mongo as a cluster, and 1 to issue mongo commands to others for setup

version: '3'
services:
    mongo-2:
        container_name: "mongo-2"
        image: mongo
        ports:
            - "30002:27017"
        command: mongod --replSet rs1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-3:
        container_name: "mongo-3"
        image: mongo
        ports:
            - "30003:27017"
        command: mongod --replSet rs1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        restart: always

    mongo-1:
        container_name: "mongo-1"
        image: mongo
        volumes:
          - ./data:/data/db
        ports:
            - "30001:27017"
        command: mongod --replSet rs1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles --dbpath /data/db
        links:
            - mongo-2:mongo-2
            - mongo-3:mongo-3
        restart: always

    mongo-rs1-setup:
        container_name: "mongo-rs1-setup"
        image: mongo
        depends_on:
            - "mongo-1"
            - "mongo-2"
            - "mongo-3"
        links:
            - mongo-1:mongo-1
            - mongo-2:mongo-2
            - mongo-3:mongo-3
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongo-1
            - MONGO2=mongo-2
            - MONGO3=mongo-3
            - RS=rs1
        entrypoint: ["/scripts/db-setup.sh"]
