apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-db
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-db
    spec:
      containers:
      - image: mongo
        name: mongo-db
        ports:
        - name: mongo-db
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          gcePersistentDisk:
            pdName: mongo-disk
            fsType: ext4